version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Installing Terraform"
      - curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
      - sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
      - sudo apt-get update && sudo apt-get install terraform

  pre_build:
    commands:
      - echo "Pre-build phase"
      - cd terraform/environments/multi-env

  build:
    commands:
      - echo "Build phase - just testing YAML parsing"
      - terraform init
      - terraform workspace new prod || terraform workspace select prod
      - terraform validate
      - echo "Build completed successfully"